# Generated by Django 3.0.3 on 2020-02-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerShop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contactinfo',
        ),
    ]
