# Generated by Django 3.0.3 on 2020-02-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerShop', '0002_auto_20200213_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='added_date',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='file',
            field=models.ImageField(default='', upload_to='profile'),
        ),
    ]
