# Generated by Django 3.0.3 on 2020-02-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerShop', '0004_signupinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupinfo',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
